### ISSUE TITLE
library/alpine:3.7": rpc error for eu-west-1 aws region

### ISSUE THREAD

**Issue by rampatnaik** [distribution/distribution-library-image#117] opened 2021-01-06 14:12 UTC
Hello 

I am using eks : eu-west-1

I am getting error
eu-west-1.compute.internal  Failed to pull image "registry.hub.docker.com/library/alpine:3.7": rpc error: code = Unknown desc = Error response from daemon: Get https://registry.hub.docker.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

eu-west-1.compute.internal  Back-off pulling image "registry.hub.docker.com/library/alpine:3.7"

**Comment by milosgajdos** [comment] 2024-08-14 16:41
Closing as dupe of https://github.com/distribution/distribution-library-image/issues/63

**Closed by milosgajdos** 2024-08-14 16:41 UTC
